services:
  app:
    build:
      context: .
    stdin_open: true
    tty: true
    ports:
      - '8081:8081'
    volumes:
      - ./:/opt/app:delegated
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - notused:/opt/app/node_modules
    healthcheck:
      disable: true

volumes:
  notused:
